#!/bin/bash

set -e

projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"
cd ./fcp-mpdp-backend && \
  docker compose build

cd "${projectRoot}"
cd ./fcp-mpdp-frontend && \
  docker compose build