#!/bin/bash

set -e

echo "Available commands for fcp-mpdp-core"
echo "---------------------------------------------------------------------------------------------------------------------------------------------"
echo "Command   |   Description"
echo "---------------------------------------------------------------------------------------------------------------------------------------------"
echo "./help    |   List all available commands."
echo "./clone   |   Clone all repositories from GitHub. Repositories will be cloned in the parent directory of this repository."
echo "./update  |   Switch to main branch in every repository and pull latest changes with git pull."
echo "./pull    |   Pull latest changes from current branch in every repository with git pull."
echo "./build   |   Build/rebuild Docker container for all microservices."
echo "./start   |   Run all services in detached mode."
echo "          |     Optional arguments:     -jt or --journey-tests                           Trigger local test run of journey test suite."       
echo "          |                             -pt or --performance-tests                       Trigger local test run of performance test suite."
echo "          |                             -jt -pt or --journey-tests --performance-tests   Trigger local test run of all test suites."
echo "          |                             Any valid docker compose down argument"
echo "./stop    |   Stop all services."
echo "          |     Optional arguments:     Any valid docker compose down argument"
echo "./open    |   Open all microservices in Visual Studio Code."
echo "./version |   List latest GitHub release/tag version for each microservice."
echo "---------------------------------------------------------------------------------------------------------------------------------------------"