#!/bin/bash

set -e

projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"
cd ./fcp-mpdp-backend && \
  docker compose --profile app down $@

cd "${projectRoot}"
cd ./fcp-mpdp-frontend && \
  docker compose --profile app down $@

cd "${projectRoot}"
cd ./fcp-mpdp-admin && \
  docker compose --profile app down $@


cd "${projectRoot}"
cd ./fcp-mpdp-performance-test-suite && \
  docker compose down $@
