#!/bin/bash

set -e

projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"
cd ./fcp-mpdp-backend && \
  git checkout main && \
  git pull

cd "${projectRoot}"
cd ./fcp-mpdp-frontend && \
  git checkout main && \
  git pull

cd "${projectRoot}"
cd ./fcp-mpdp-journey-test-suite && \
  git checkout main && \
  git pull

cd "${projectRoot}"
cd ./fcp-mpdp-performance-test-suite && \
  git checkout main && \
  git pull